### ISSUE TITLE
how to use snapcraft - python apt dependency

### ISSUE THREAD

**Issue by stuart-warren** [jnsgruk/crafts-flake#51]
I'm a little confused how to get snapcraft working from this flake

```sh
$ snapcraft
Traceback (most recent call last):
  File "/nix/store/0kyllz1bdz1snrgiik1m508dfgpaliri-snapcraft-8.0.4/bin/..snapcraft-wrapped-wrapped", line 6, in <module>
    from snapcraft.cli import run
  File "/nix/store/0kyllz1bdz1snrgiik1m508dfgpaliri-snapcraft-8.0.4/lib/python3.11/site-packages/snapcraft/__init__.py", line 23, in <module>
    import snapcraft.sources  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0kyllz1bdz1snrgiik1m508dfgpaliri-snapcraft-8.0.4/lib/python3.11/site-packages/snapcraft/sources.py", line 22, in <module>
    from snapcraft_legacy.sources import get
  File "/nix/store/0kyllz1bdz1snrgiik1m508dfgpaliri-snapcraft-8.0.4/lib/python3.11/site-packages/snapcraft_legacy/__init__.py", line 340, in <module>
    from snapcraft_legacy.internal import repo  # noqa isort:skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0kyllz1bdz1snrgiik1m508dfgpaliri-snapcraft-8.0.4/lib/python3.11/site-packages/snapcraft_legacy/internal/repo/__init__.py", line 27, in <module>
    from ._deb import Ubuntu  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0kyllz1bdz1snrgiik1m508dfgpaliri-snapcraft-8.0.4/lib/python3.11/site-packages/snapcraft_legacy/internal/repo/_deb.py", line 39, in <module>
    from .apt_cache import AptCache
  File "/nix/store/0kyllz1bdz1snrgiik1m508dfgpaliri-snapcraft-8.0.4/lib/python3.11/site-packages/snapcraft_legacy/internal/repo/apt_cache.py", line 25, in <module>
    import apt
ModuleNotFoundError: No module named 'apt'
```

There is no obvious pythonPackages.apt package in the nix store

using the following nix shell flake
```nix
{
  description = "A Nix-flake-based snap development environment";

  inputs = {
    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0.1.*.tar.gz";
    crafts.url = "github:jnsgruk/crafts-flake";
    crafts.inputs.nixpkgs.follows = "nixpkgs";

  };

  outputs = { self, nixpkgs, crafts }:
    let
      supportedSystems =
        [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forEachSupportedSystem = f:
        nixpkgs.lib.genAttrs supportedSystems (system:
          f {
            pkgs = import nixpkgs {
              inherit system;
              overlays = [ crafts.overlay ];
            };
          });
    in
    {
      devShells = forEachSupportedSystem ({ pkgs }: {
        default =
          pkgs.mkShell { packages = with pkgs; [ apt shellcheck snapcraft ]; };
      });
    };
}
```

is there some environment var or setting in snapcraft.yaml to avoid the snapcraft_legacy module perhaps?

thanks

**Comment by jnsgruk** [comment]
Ah interesting. Can you post the snapcraft.yaml you're using?

**Comment by stuart-warren** [comment]
just the tutorial one
```
name: hello
base: core22
version: '2.10'
summary: GNU Hello, the "hello world" snap
description: |
  GNU hello prints a friendly greeting.
grade: stable
confinement: strict
apps:
  hello:
    command: bin/hello
parts:
  gnu-hello:
    source: http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
    plugin: autotools
```

thanks

**Comment by jnsgruk** [comment]
Weird. Not seen this. Won't get to it tonight but I'll have a play and report back soon. Thanks for reporting!

**Comment by jnsgruk** [comment]
I had a go at reproducing this today, and it seemed to work fine :man_shrugging: (well, aside from the fact that the example is actually a little broken I think).

```
 ~/temp/snapcraft-test
❯ cat flake.nix
{
  description = "A Nix-flake-based snap development environment";

  inputs = {
    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0.1.*.tar.gz";
    crafts.url = "github:jnsgruk/crafts-flake";
    crafts.inputs.nixpkgs.follows = "nixpkgs";

  };

  outputs = { self, nixpkgs, crafts }:
    let
      supportedSystems =
        [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forEachSupportedSystem = f:
        nixpkgs.lib.genAttrs supportedSystems (system:
          f {
            pkgs = import nixpkgs {
              inherit system;
              overlays = [ crafts.overlay ];
            };
          });
    in
    {
      devShells = forEachSupportedSystem ({ pkgs }: {
        default =
          pkgs.mkShell { packages = with pkgs; [ apt shellcheck snapcraft ]; };
      });
    };
}

 ~/temp/snapcraft-test
❯ cat snapcraft.yaml
name: hello
base: core22
version: '2.10'
summary: GNU Hello, the "hello world" snap
description: |
  GNU hello prints a friendly greeting.
grade: stable
confinement: strict
apps:
  hello:
    command: bin/hello
parts:
  gnu-hello:
    source: http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
    plugin: autotools

 ~/temp/snapcraft-test
❯ nix develop

[jon@freyja:~/temp/snapcraft-test]$ snapcraft
Using snapcraft from snap store channel 'latest/stable' in instance because snap injection is only supported on Linux hosts.
Generated snap metadata
...
```

Can you confirm how you're entering the dev shell, are you using `nix develop`?

**Comment by stuart-warren** [comment]
I was using direnv `use flake`, but `nix develop` also seems to fail in the same way for me

Are you able to explain where the nix source for `python-apt` comes from please? thanks

I don't see a mention to in in this repo and I don't see anything in the unstable nix packages

**Comment by jnsgruk** [comment]
It doesn't seem to be included. I've opened #53 - can you please point your `flake.nix` to that commit and give it another test to see if it solves the problem for you?

Something like:

```nix
inputs = {
    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0.1.*.tar.gz";
    crafts.url = "github:jnsgruk/crafts-flake/python-apt-bindings";
    crafts.inputs.nixpkgs.follows = "nixpkgs";
};
```

**Comment by jnsgruk** [comment]
No probs!
